import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/public-config.ts",
    "src/envconfig.ts",
    "src/ports.ts",
    "src/timezone.ts",
    "src/duration.ts",
    "src/permissions.ts",
    "src/dashboard.ts",
    "src/users.ts",
    "src/locales.ts",
    "src/enums/index.ts",
    "src/issuance/index.ts",
    "src/validation/index.ts",
    "src/sanitize.ts",
    "src/console/index.ts",
    "src/build.ts",
    "src/vite.ts",
    "src/primevue.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
  target: "es2021",
});
