packages:
  - 'workspaces/*'

nodeLinker: hoisted
engineStrict: true
strictPeerDependencies: false
autoInstallPeers: true

overrides:
  canvas: ^3.1.0
  discord-api-types: 0.38.49
  fastify: ^5.8.5
  '@nestjs/swagger>js-yaml': ^5.2.2
  mailparser>nodemailer: ^9.0.4
  mailparser>linkify-it: ^5.0.2
  tsup>esbuild: ^0.28.1
  bundle-require>esbuild: ^0.28.1

peerDependencyRules:
  ignoreMissing:
    - fastify

allowBuilds:
  '@parcel/watcher': true
  bcrypt: true
  canvas: true
  esbuild: true
  '@scarf/scarf': false
  core-js: false
  es5-ext: false
