export enum ConfigField {
  LauncherExe = 'public_launcher_exe',
  LauncherJar = 'public_launcher_jar',
  EconomyRate = 'public_economy_rate',
  ReferalTrigger = 'public_referal_trigger',
  ReferalReward = 'public_referal_reward',
  ReferalRewardPlayer = 'public_referal_reward_player',
  LinkForum = 'public_link_forum',
  LinkDiscord = 'public_link_discord',
  LinkVk = 'public_link_vk',
  LinkTelegram = 'public_link_telegram',
  LinkYoutube = 'public_link_youtube',
  LinkMctop = 'public_link_mctop',
  LinkTopcraft = 'public_link_topcraft',
  LinkMinecraftraiting = 'public_link_minecraftraiting',
  MonitoringReward = 'public_monitoring_reward',
  UnbanPrice = 'public_unban_price',
  VirtualPercent = 'public_virtual_percent',
  VotesTwinkProtect = 'public_votes_twink_protect',
  StoreKitsVirtualUse = 'public_store_kits_virtual_use',
  StoreProductsVirtualUse = 'public_store_products_virtual_use',
  DonateGroupsVirtualUse = 'public_donate_groups_virtual_use',
  DonatePermsVirtualUse = 'public_donate_perms_virtual_use',
  EmailActivationRequired = 'public_email_activation_required',
  OrdinaryRegister = 'public_ordinary_register',
  RconPreset = 'rcon_preset',
  RconTplGiveItem = 'rcon_tpl_give_item',
  RconTplGroupAdd = 'rcon_tpl_group_add',
  RconTplGroupAddTemp = 'rcon_tpl_group_add_temp',
  RconTplGroupRemove = 'rcon_tpl_group_remove',
  RconTplPermSet = 'rcon_tpl_perm_set',
  RconTplPermSetTemp = 'rcon_tpl_perm_set_temp',
  RconTplPermUnset = 'rcon_tpl_perm_unset',
}

export enum ConfigType {
  number,
  string,
  boolean,
}
